[package]
name = "fifteen-puzzle"
version = "0.0.0"
edition = "2021"

[dependencies]
itoa = "1.0.5"
serde = "1.0.152"
serde_json = "1.0.92"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = "fat"
strip = "symbols"
